### ISSUE TITLE
provide API Key authentication

### ISSUE THREAD

**Issue by boaglio** [boaglio/DBaaS#5]
- services should send **apikey** in HTTP header
- API Key should be in UUID format and placed at _application.yaml_:

```
# default server port
server:
  port: 8080
# API Key
dbass:
  apikey:  78aa3a04-1f0f-11ec-9621-0242ac130002
```
